export const ROUTES = {
  API: {
    AUTH: "/auth",
    OTP: "/otp",
    ROLES: "/roles",
    RESTRICTIONS: "/restrictions",
    USER: "/user",
    HEALTH: "/health",
    LANGUAGE: "/language",
    SKILLS: "/skills",
    SUBSCRIPTION: "/subscription",
    EXPERIENCE: "/experience",
    EDUCATION: "/education",
    WORKER: "/worker",
    BUSINESS: "/business",
    JOBS: "/jobs",
    ADMIN: "/admin",
    REPORTS: "/reports",
    ADMIN_REPORTS: "/admin-reports",
    CERTIFICATE: "/certificate",
  },
  ADMIN: {
    STATISTICS: {
      ROOT: "/statistics",
      GET_ALL: "/dashboard-statistics",
    },
    BUSINESS: {
      ROOT: "/business",
      GET_ALL: "/get-all-businesses",
      TOGGLE_BLOCK: "/toggle-block/:businessId",
    },
    WORKER: {
      ROOT: "/worker",
      GET_ALL: "/get-all-workers",
      TOGGLE_BLOCK: "/toggle-block/:workerId",
    },
    JOB: {
      ROOT: "/jobs",
      GET_ALL: "/get-all-jobs",
      TOGGLE_BLOCK: "/toggle-block/:jobId",
      GET_By_ID: "/get-by-id/:jobId",
    },
    REPORT: {
      ROOT: "/report",
      GET_ALL: "/get-all-reports",
      GET_BUSINESS_REPORTS: "/get-business-reports",
      GET_WORKER_REPORTS: "/get-worker-reports",
      GET_JOB_REPORTS: "/get-job-reports",
      GET_SINGLE_WORKER_REPORT: "/get-single-worker-report/:reportId",
      GET_SINGLE_BUSINESS_REPORT: "/get-single-business-report/:reportId",
      GET_SINGLE_JOB_REPORT: "/get-single-job-report/:reportId",
    },
  },
  AUTH: {
    SIGNUP: "/sign-up",
    SIGNIN: "/sign-in",
    RESET_PASSWORD: "/reset-password",
    DELETE_ACCOUNT: "/delete-account",
    REFRESH: "/refresh",
    PASSWORD_RECOVERY: "/password-recovery",
    LOGOUT: "/logout",
    IS_AUTHENTICATED: "/is-authenticated",
    OAUTH: "/oauth",
  },
  LANGUAGE: {
    CREATE: "/create",
    UPDATE: "/update",
    DELETE: "/delete",
    UPDATE_ALL: "/update-all",
  },
  OAUTH: {
    GOOGLE: "/google",
    GOOGLE_CALLBACK: "/google/callback",
  },
  OTP: {
    SEND_OTP: "/send-otp",
    VERIFY_OTP: "/verify-otp",
  },
  USER: {
    CURRENT_USER: "/current-user",
    UPDATE_USER: "/update-user",
    TOGGLE_FIRST_TIME_LOGIN: "/toggle-first-time-login",
    DELETE_ACCOUNT: "/delete-account",
    FORGOT_PASSWORD: "/forgot-password",
    VERIFY_OTP: "/verify-otp",
    RESET_PASSWORD: "/reset-password",
    GET_WORKER_PROFILE_DETAILS: "/worker-profile-details",
    GET_BUSINESS_PROFILE_DETAILS: "/business-profile-details",
    GET_WORKER_APPLIED_JOBS: "/applied-jobs",
  },
  ROLE: {
    UPDATE_ROLE: "/:id",
  },
  RESTRICTION: {
    ROOT: "/",
    USER_RESTRICTIONS: "/:user-id",
  },
  BUSINESS_PROFILE: {
    UPDATE_BUSINESS_PROFILE: "/update-business-profile",
    GET_ALL_BUSINESS_PROFILES: "/get-all-business-profiles",
    GET_BUSINESS_PROFILE_DETAILS: "/business-profile-details/:businessId",
    GET_ALL_BUSINESS_JOBS: "/get-all-business-jobs",
    GET_JOB_DETAILS: "/job-details/:jobId",
    TOGGLE_JOB_STATUS: "/toggle-job-status/:jobId",
    GET_PROFILE_PICTURE_UPLOAD_URL: "/get-profile-picture-upload-url",
    SAVE_PROFILE_PICTURE: "/save-profile-picture",
    GET_ASSET_UPLOAD_URL: "/get-asset-upload-url",
    SAVE_ASSETS: "/save-assets",
    DELETE_ASSETS: "/delete-assets",
  },
  WROKER_SKILLS: {
    CREATE: "/",
    GET_ALL: "/",
    UPDATE: "/",
    DELETE: "/",
  },
  WORKER_EXPERIENCE: {
    CREATE: "/",
    GET_ALL: "/",
    UPDATE: "/",
    DELETE: "/",
    UPDATE_ALL: "/update-all",
  },
  WORKER_EDUCATIONS: {
    CREATE: "/",
    GET_ALL: "/",
    UPDATE: "/",
    DELETE: "/",
    UPDATE_ALL: "/update-all",
  },
  WORKER_PROFILE: {
    GET_ALL: "/get-all-workers-profiles",
    GET_DETAILS: "/:workerId",
    UPDATE_WORKER_PROFILE: "/update-worker-profile",
    GET_PROFILE_PICTURE_UPLOAD_URL: "/profile-picture-upload-url",
    SAVE_PROFILE_PICTURE: "/save-profile-picture",
  },
  JOBS: {
    CREATE: "/create",
    GET_ALL: "/get-all-jobs",
    GET_DETAILS: "/:jobId",
    UPDATE: "/update/:jobId",
    DELETE: "/delete/:jobId",
    APPLY: "/apply/:jobId",
    GET_APPLICANTS_OF_JOB: "/get-applicants-of-job/:jobId",
  },
  REPORT: {
    ROOT: "/report",
    REPORT_WORKER: "/report-worker/:workerId",
    REPORT_BUSINESS: "/report-business/:businessId",
    REPORT_JOB: "/report-job/:jobId",
    HAS_WORKER_REPORTED_JOB: "/has-reported-job/:jobId",
    HAS_WORKER_REPORTED_BUSINESS: "/has-reported-business/:businessId",
    HAS_BUSINESS_REPORTED_WORKER: "/has-reported-worker/:workerId",
  },
  CERTIFICATE: {
    CREATE: "/create",
    DELETE: "/delete",
    GET_ASSET_UPLOAD_URL: "/get-asset-upload-url",
    SAVE_ASSETS: "/save-assets",
  },
} as const;
