/*
  Warnings:

  - You are about to drop the column `categoryId` on the `jobs` table. All the data in the column will be lost.
  - You are about to drop the `categories` table. If the table is not empty, all the data it contains will be lost.
  - You are about to drop the `skills` table. If the table is not empty, all the data it contains will be lost.
  - You are about to drop the `worker_categories` table. If the table is not empty, all the data it contains will be lost.

*/
-- DropForeignKey
ALTER TABLE `jobs` DROP FOREIGN KEY `jobs_categoryId_fkey`;

-- DropForeignKey
ALTER TABLE `skills` DROP FOREIGN KEY `skills_categoryId_fkey`;

-- DropForeignKey
ALTER TABLE `worker_categories` DROP FOREIGN KEY `worker_categories_categoryId_fkey`;

-- DropForeignKey
ALTER TABLE `worker_categories` DROP FOREIGN KEY `worker_categories_workerId_fkey`;

-- AlterTable
ALTER TABLE `jobs` DROP COLUMN `categoryId`;

-- DropTable
DROP TABLE `categories`;

-- DropTable
DROP TABLE `skills`;

-- DropTable
DROP TABLE `worker_categories`;

-- CreateTable
CREATE TABLE `worker_skills` (
    `id` VARCHAR(191) NOT NULL,
    `workerId` VARCHAR(191) NOT NULL,
    `skillName` ENUM('PIPE_INSTALLATION', 'DRAIN_CLEANING', 'FIXTURE_INSTALLATION', 'WATER_HEATER_SERVICE', 'LEAK_REPAIR', 'WIRING_INSTALLATION', 'LIGHTING_INSTALLATION', 'ELECTRICAL_REPAIR', 'PANEL_UPGRADES', 'GENERATOR_INSTALLATION', 'CABINET_MAKING', 'FRAMING', 'FINISH_CARPENTRY', 'DOOR_INSTALLATION', 'WINDOW_INSTALLATION', 'AC_INSTALLATION', 'HEATING_REPAIR', 'VENTILATION_WORK', 'DUCT_CLEANING', 'SYSTEM_MAINTENANCE', 'INTERIOR_PAINTING', 'EXTERIOR_PAINTING', 'WALLPAPER_INSTALLATION', 'STAINING', 'PAINT_REMOVAL', 'LAWN_MAINTENANCE', 'TREE_TRIMMING', 'GARDEN_DESIGN', 'IRRIGATION_INSTALLATION', 'HARDSCAPING', 'DEEP_CLEANING', 'WINDOW_CLEANING', 'CARPET_CLEANING', 'PRESSURE_WASHING', 'SANITIZATION', 'FURNITURE_MOVING', 'PACKING_SERVICES', 'HEAVY_LIFTING', 'EQUIPMENT_TRANSPORTATION', 'LOGISTICS_PLANNING', 'ENGINE_REPAIR', 'BRAKE_SERVICE', 'TRANSMISSION_REPAIR', 'AUTO_ELECTRICAL', 'BODY_WORK', 'ROOF_INSTALLATION', 'SHINGLE_REPAIR', 'LEAK_DETECTION', 'GUTTER_INSTALLATION', 'ROOF_INSPECTION', 'BRICK_LAYING', 'STONE_WORK', 'CONCRETE_POURING', 'FOUNDATION_REPAIR', 'TUCKPOINTING', 'ARC_WELDING', 'MIG_WELDING', 'TIG_WELDING', 'PIPE_WELDING', 'STRUCTURAL_WELDING', 'TILE_INSTALLATION', 'HARDWOOD_FLOORING', 'CARPET_INSTALLATION', 'VINYL_FLOORING', 'FLOOR_REFINISHING', 'INSECT_EXTERMINATION', 'RODENT_CONTROL', 'TERMITE_TREATMENT', 'WILDLIFE_REMOVAL', 'PREVENTATIVE_TREATMENTS', 'REFRIGERATOR_REPAIR', 'WASHER_DRYER_SERVICE', 'DISHWASHER_REPAIR', 'OVEN_REPAIR', 'MICROWAVE_SERVICE', 'HANDYMAN_SERVICES', 'PROPERTY_MAINTENANCE', 'PREVENTATIVE_MAINTENANCE', 'EQUIPMENT_SERVICING', 'FACILITY_UPKEEP', 'SUPERVISOR', 'CONSTRUCTION_MANAGER', 'PROJECT_MANAGEMENT', 'TEAM_LEADERSHIP', 'RESOURCE_PLANNING', 'BUILDING_INSPECTION', 'SAFETY_INSPECTION', 'QUALITY_CONTROL', 'CODE_COMPLIANCE', 'STRUCTURAL_ASSESSMENT', 'INSTRUMENT_TECHNICIAN', 'MAINTENANCE_TECHNICIAN', 'ELECTRONICS_TECHNICIAN', 'CALIBRATION_SPECIALIST', 'EQUIPMENT_DIAGNOSTICS', 'PIPEFITTING', 'METAL_FABRICATION', 'WELDING_ASSEMBLY', 'STRUCTURAL_FABRICATION', 'CUSTOM_FABRICATION', 'EQUIPMENT_REPAIR', 'MECHANICAL_OVERHAUL', 'PLANT_MAINTENANCE', 'PREVENTIVE_MAINTENANCE', 'EXCAVATION', 'TRENCHING', 'SITE_CLEARANCE', 'LAND_GRADING', 'DEWATERING', 'CRANE_OPERATION', 'SLINGING', 'WINCHING', 'HOISTING', 'SCAFFOLD_RIGGING') NOT NULL,
    `createdAt` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),

    UNIQUE INDEX `worker_skills_workerId_skillName_key`(`workerId`, `skillName`),
    PRIMARY KEY (`id`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE `job_skills` (
    `id` VARCHAR(191) NOT NULL,
    `jobId` VARCHAR(191) NOT NULL,
    `skillName` ENUM('PIPE_INSTALLATION', 'DRAIN_CLEANING', 'FIXTURE_INSTALLATION', 'WATER_HEATER_SERVICE', 'LEAK_REPAIR', 'WIRING_INSTALLATION', 'LIGHTING_INSTALLATION', 'ELECTRICAL_REPAIR', 'PANEL_UPGRADES', 'GENERATOR_INSTALLATION', 'CABINET_MAKING', 'FRAMING', 'FINISH_CARPENTRY', 'DOOR_INSTALLATION', 'WINDOW_INSTALLATION', 'AC_INSTALLATION', 'HEATING_REPAIR', 'VENTILATION_WORK', 'DUCT_CLEANING', 'SYSTEM_MAINTENANCE', 'INTERIOR_PAINTING', 'EXTERIOR_PAINTING', 'WALLPAPER_INSTALLATION', 'STAINING', 'PAINT_REMOVAL', 'LAWN_MAINTENANCE', 'TREE_TRIMMING', 'GARDEN_DESIGN', 'IRRIGATION_INSTALLATION', 'HARDSCAPING', 'DEEP_CLEANING', 'WINDOW_CLEANING', 'CARPET_CLEANING', 'PRESSURE_WASHING', 'SANITIZATION', 'FURNITURE_MOVING', 'PACKING_SERVICES', 'HEAVY_LIFTING', 'EQUIPMENT_TRANSPORTATION', 'LOGISTICS_PLANNING', 'ENGINE_REPAIR', 'BRAKE_SERVICE', 'TRANSMISSION_REPAIR', 'AUTO_ELECTRICAL', 'BODY_WORK', 'ROOF_INSTALLATION', 'SHINGLE_REPAIR', 'LEAK_DETECTION', 'GUTTER_INSTALLATION', 'ROOF_INSPECTION', 'BRICK_LAYING', 'STONE_WORK', 'CONCRETE_POURING', 'FOUNDATION_REPAIR', 'TUCKPOINTING', 'ARC_WELDING', 'MIG_WELDING', 'TIG_WELDING', 'PIPE_WELDING', 'STRUCTURAL_WELDING', 'TILE_INSTALLATION', 'HARDWOOD_FLOORING', 'CARPET_INSTALLATION', 'VINYL_FLOORING', 'FLOOR_REFINISHING', 'INSECT_EXTERMINATION', 'RODENT_CONTROL', 'TERMITE_TREATMENT', 'WILDLIFE_REMOVAL', 'PREVENTATIVE_TREATMENTS', 'REFRIGERATOR_REPAIR', 'WASHER_DRYER_SERVICE', 'DISHWASHER_REPAIR', 'OVEN_REPAIR', 'MICROWAVE_SERVICE', 'HANDYMAN_SERVICES', 'PROPERTY_MAINTENANCE', 'PREVENTATIVE_MAINTENANCE', 'EQUIPMENT_SERVICING', 'FACILITY_UPKEEP', 'SUPERVISOR', 'CONSTRUCTION_MANAGER', 'PROJECT_MANAGEMENT', 'TEAM_LEADERSHIP', 'RESOURCE_PLANNING', 'BUILDING_INSPECTION', 'SAFETY_INSPECTION', 'QUALITY_CONTROL', 'CODE_COMPLIANCE', 'STRUCTURAL_ASSESSMENT', 'INSTRUMENT_TECHNICIAN', 'MAINTENANCE_TECHNICIAN', 'ELECTRONICS_TECHNICIAN', 'CALIBRATION_SPECIALIST', 'EQUIPMENT_DIAGNOSTICS', 'PIPEFITTING', 'METAL_FABRICATION', 'WELDING_ASSEMBLY', 'STRUCTURAL_FABRICATION', 'CUSTOM_FABRICATION', 'EQUIPMENT_REPAIR', 'MECHANICAL_OVERHAUL', 'PLANT_MAINTENANCE', 'PREVENTIVE_MAINTENANCE', 'EXCAVATION', 'TRENCHING', 'SITE_CLEARANCE', 'LAND_GRADING', 'DEWATERING', 'CRANE_OPERATION', 'SLINGING', 'WINCHING', 'HOISTING', 'SCAFFOLD_RIGGING') NOT NULL,
    `createdAt` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),

    UNIQUE INDEX `job_skills_jobId_skillName_key`(`jobId`, `skillName`),
    PRIMARY KEY (`id`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- AddForeignKey
ALTER TABLE `worker_skills` ADD CONSTRAINT `worker_skills_workerId_fkey` FOREIGN KEY (`workerId`) REFERENCES `worker_profiles`(`id`) ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE `job_skills` ADD CONSTRAINT `job_skills_jobId_fkey` FOREIGN KEY (`jobId`) REFERENCES `jobs`(`id`) ON DELETE CASCADE ON UPDATE CASCADE;
