-- AlterTable
ALTER TABLE `block` ADD COLUMN `reportId` VARCHAR(191) NULL,
    ADD COLUMN `reportType` ENUM('HARASSMENT', 'SPAM', 'INAPPROPRIATE_CONTENT', 'FRAUD', 'FAKE_PROFILE', 'HATE_SPEECH', 'VIOLENCE', 'INTELLECTUAL_PROPERTY', 'IMPERSONATION', 'OTHER') NULL,
    MODIFY `reason` TEXT NULL;

-- AlterTable
ALTER TABLE `reports` ADD COLUMN `reportType` ENUM('HARASSMENT', 'SPAM', 'INAPPROPRIATE_CONTENT', 'FRAUD', 'FAKE_PROFILE', 'HATE_SPEECH', 'VIOLENCE', 'INTELLECTUAL_PROPERTY', 'IMPERSONATION', 'OTHER') NOT NULL DEFAULT 'OTHER';

-- AddForeignKey
ALTER TABLE `Block` ADD CONSTRAINT `Block_reportId_fkey` FOREIGN KEY (`reportId`) REFERENCES `reports`(`id`) ON DELETE SET NULL ON UPDATE CASCADE;
