-- AlterTable
ALTER TABLE `job_applications` ADD COLUMN `duration` ENUM('LESS_THAN_ONE_WEEK', 'ONE_2_TWO_WEEKS', 'TWO_2_FOUR_WEEKS', 'ONE_2_THREE_MONTHS', 'MORE_THAN_THREE_MONTHS') NOT NULL DEFAULT 'LESS_THAN_ONE_WEEK';
