-- CreateTable
CREATE TABLE `users` (
    `id` VARCHAR(191) NOT NULL,
    `email` VARCHAR(191) NOT NULL,
    `password` VARCHAR(191) NOT NULL,
    `firstName` VARCHAR(191) NOT NULL,
    `lastName` VARCHAR(191) NOT NULL,
    `createdAt` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    `updatedAt` DATETIME(3) NOT NULL,
    `isVerified` BOOLEAN NOT NULL DEFAULT false,
    `isDeleted` BOOLEAN NOT NULL DEFAULT false,
    `isSuspended` BOOLEAN NOT NULL DEFAULT false,
    `role` ENUM('WORKER', 'BUSINESS', 'ADMIN', 'SUPER_ADMIN', 'DEVELOPER') NOT NULL DEFAULT 'WORKER',
    `provider` ENUM('GOOGLE', 'OUTLOOK', 'FACEBOOK', 'GITHUB', 'EMAIL_PASSWORD') NOT NULL DEFAULT 'EMAIL_PASSWORD',
    `defaultProfile` ENUM('WORKER', 'BUSINESS') NOT NULL DEFAULT 'WORKER',
    `firstTimeLogin` BOOLEAN NOT NULL DEFAULT true,

    UNIQUE INDEX `users_email_key`(`email`),
    PRIMARY KEY (`id`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE `worker_profiles` (
    `id` VARCHAR(191) NOT NULL,
    `userId` VARCHAR(191) NOT NULL,
    `title` VARCHAR(191) NULL,
    `description` TEXT NULL,
    `city` VARCHAR(191) NULL,
    `state` VARCHAR(191) NULL,
    `createdAt` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    `updatedAt` DATETIME(3) NOT NULL,
    `country` VARCHAR(191) NULL,
    `hourlyRate` DOUBLE NULL,
    `availability` BOOLEAN NOT NULL DEFAULT true,
    `totalEarnings` DOUBLE NOT NULL DEFAULT 0,
    `completedJobs` INTEGER NOT NULL DEFAULT 0,
    `avgRating` DOUBLE NOT NULL DEFAULT 0,
    `onboardingStep` ENUM('PERSONAL_INFO', 'SKILLS_HOURLY_RATE_INFO', 'EXPERIENCE_INFO', 'EDUCATION_INFO', 'LANGUAGE_INFO', 'AVAILABILITY_INFO', 'COMPLETED') NOT NULL DEFAULT 'PERSONAL_INFO',

    UNIQUE INDEX `worker_profiles_userId_key`(`userId`),
    PRIMARY KEY (`id`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE `profile_pictures` (
    `id` VARCHAR(191) NOT NULL,
    `workerProfileId` VARCHAR(191) NOT NULL,
    `s3Key` VARCHAR(191) NOT NULL,
    `createdAt` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    `updatedAt` DATETIME(3) NOT NULL,

    UNIQUE INDEX `profile_pictures_workerProfileId_key`(`workerProfileId`),
    PRIMARY KEY (`id`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE `business_profiles` (
    `id` VARCHAR(191) NOT NULL,
    `userId` VARCHAR(191) NOT NULL,
    `companyName` VARCHAR(191) NULL,
    `description` TEXT NULL,
    `industry` VARCHAR(191) NULL,
    `city` VARCHAR(191) NULL,
    `state` VARCHAR(191) NULL,
    `country` VARCHAR(191) NULL,
    `website` VARCHAR(191) NULL,
    `employeeCount` INTEGER NULL,
    `yearFounded` INTEGER NULL,
    `totalSpent` DOUBLE NOT NULL DEFAULT 0,
    `postedJobs` INTEGER NOT NULL DEFAULT 0,
    `onboardingStep` ENUM('COMPANY_INFO', 'COMPLETED') NOT NULL DEFAULT 'COMPANY_INFO',

    UNIQUE INDEX `business_profiles_userId_key`(`userId`),
    PRIMARY KEY (`id`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE `user_restrictions` (
    `id` VARCHAR(191) NOT NULL,
    `userId` VARCHAR(191) NOT NULL,
    `restrictionType` ENUM('APPLY_TO_JOBS', 'SEND_MESSAGES', 'POST_JOBS', 'HIRE_WORKERS', 'VIEW_PROFILES', 'SUBMIT_REVIEWS', 'SUBMIT_REPORTS') NOT NULL,
    `createdAt` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    `expiresAt` DATETIME(3) NULL,
    `reason` TEXT NULL,

    UNIQUE INDEX `user_restrictions_userId_restrictionType_key`(`userId`, `restrictionType`),
    PRIMARY KEY (`id`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE `conversations` (
    `id` VARCHAR(191) NOT NULL,
    `workerProfileId` VARCHAR(191) NOT NULL,
    `businessProfileId` VARCHAR(191) NOT NULL,
    `createdAt` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    `updatedAt` DATETIME(3) NOT NULL,

    UNIQUE INDEX `conversations_workerProfileId_businessProfileId_key`(`workerProfileId`, `businessProfileId`),
    PRIMARY KEY (`id`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE `messages` (
    `id` VARCHAR(191) NOT NULL,
    `conversationId` VARCHAR(191) NOT NULL,
    `senderWorkerId` VARCHAR(191) NULL,
    `senderBusinessId` VARCHAR(191) NULL,
    `receiverWorkerId` VARCHAR(191) NULL,
    `receiverBusinessId` VARCHAR(191) NULL,
    `content` TEXT NOT NULL,
    `isRead` BOOLEAN NOT NULL DEFAULT false,
    `createdAt` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),

    PRIMARY KEY (`id`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE `jobs` (
    `id` VARCHAR(191) NOT NULL,
    `title` VARCHAR(191) NOT NULL,
    `description` TEXT NOT NULL,
    `requirements` TEXT NOT NULL,
    `employmentType` ENUM('FULL_TIME', 'PART_TIME', 'CONTRACT', 'TEMPORARY', 'INTERNSHIP', 'FREELANCE') NOT NULL DEFAULT 'FULL_TIME',
    `numberOfPositions` INTEGER NOT NULL DEFAULT 1,
    `budget` DOUBLE NULL,
    `hourlyRateMin` DOUBLE NULL,
    `hourlyRateMax` DOUBLE NULL,
    `businessProfileId` VARCHAR(191) NOT NULL,
    `status` ENUM('OPEN', 'IN_PROGRESS', 'COMPLETED', 'CANCELLED', 'EXPIRED') NOT NULL DEFAULT 'OPEN',
    `jobType` ENUM('FULL_TIME', 'PART_TIME', 'CONTRACT', 'TEMPORARY', 'INTERNSHIP') NOT NULL DEFAULT 'FULL_TIME',
    `startDate` DATETIME(3) NULL,
    `numberOfWorkersRequired` INTEGER NOT NULL,
    `createdAt` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    `updatedAt` DATETIME(3) NOT NULL,
    `expiresAt` DATETIME(3) NULL,

    PRIMARY KEY (`id`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE `job_locations` (
    `id` VARCHAR(191) NOT NULL,
    `jobId` VARCHAR(191) NOT NULL,
    `street` VARCHAR(191) NULL,
    `city` VARCHAR(191) NOT NULL,
    `state` VARCHAR(191) NOT NULL,
    `country` VARCHAR(191) NOT NULL,
    `postalCode` VARCHAR(191) NULL,
    `isRemote` BOOLEAN NOT NULL DEFAULT false,

    UNIQUE INDEX `job_locations_jobId_key`(`jobId`),
    PRIMARY KEY (`id`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE `job_images` (
    `id` VARCHAR(191) NOT NULL,
    `jobId` VARCHAR(191) NOT NULL,
    `s3Key` VARCHAR(191) NOT NULL,
    `caption` VARCHAR(191) NULL,
    `createdAt` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),

    PRIMARY KEY (`id`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE `job_applications` (
    `id` VARCHAR(191) NOT NULL,
    `jobId` VARCHAR(191) NOT NULL,
    `workerProfileId` VARCHAR(191) NOT NULL,
    `coverLetter` TEXT NOT NULL,
    `proposedRate` DOUBLE NOT NULL,
    `status` ENUM('PENDING', 'ACCEPTED', 'REJECTED', 'WITHDRAWN') NOT NULL DEFAULT 'PENDING',
    `createdAt` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    `updatedAt` DATETIME(3) NOT NULL,

    PRIMARY KEY (`id`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE `contracts` (
    `id` VARCHAR(191) NOT NULL,
    `jobId` VARCHAR(191) NOT NULL,
    `workerProfileId` VARCHAR(191) NOT NULL,
    `businessProfileId` VARCHAR(191) NOT NULL,
    `status` ENUM('ACTIVE', 'COMPLETED', 'CANCELLED', 'DISPUTED') NOT NULL DEFAULT 'ACTIVE',
    `startDate` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    `endDate` DATETIME(3) NULL,
    `paymentRate` DOUBLE NOT NULL,
    `totalAmount` DOUBLE NOT NULL,
    `createdAt` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    `updatedAt` DATETIME(3) NOT NULL,

    PRIMARY KEY (`id`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE `milestones` (
    `id` VARCHAR(191) NOT NULL,
    `contractId` VARCHAR(191) NOT NULL,
    `title` VARCHAR(191) NOT NULL,
    `description` TEXT NOT NULL,
    `amount` DOUBLE NOT NULL,
    `dueDate` DATETIME(3) NOT NULL,
    `status` ENUM('PENDING', 'COMPLETED', 'CANCELLED') NOT NULL DEFAULT 'PENDING',
    `createdAt` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    `updatedAt` DATETIME(3) NOT NULL,

    PRIMARY KEY (`id`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE `reviews` (
    `id` VARCHAR(191) NOT NULL,
    `rating` DOUBLE NOT NULL,
    `comment` TEXT NOT NULL,
    `workerProfileId` VARCHAR(191) NULL,
    `businessProfileId` VARCHAR(191) NULL,
    `contractId` VARCHAR(191) NOT NULL,
    `createdAt` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),

    PRIMARY KEY (`id`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE `reports` (
    `id` VARCHAR(191) NOT NULL,
    `reporterWorkerId` VARCHAR(191) NULL,
    `reporterBusinessId` VARCHAR(191) NULL,
    `reportedWorkerId` VARCHAR(191) NULL,
    `reportedBusinessId` VARCHAR(191) NULL,
    `reason` TEXT NOT NULL,
    `status` ENUM('PENDING', 'UNDER_REVIEW', 'RESOLVED', 'REJECTED') NOT NULL DEFAULT 'PENDING',
    `createdAt` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    `updatedAt` DATETIME(3) NOT NULL,

    PRIMARY KEY (`id`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE `projects` (
    `id` VARCHAR(191) NOT NULL,
    `workerId` VARCHAR(191) NOT NULL,
    `title` VARCHAR(191) NOT NULL,
    `description` TEXT NOT NULL,
    `completionDate` DATETIME(3) NOT NULL,
    `projectUrl` VARCHAR(191) NULL,
    `createdAt` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),

    PRIMARY KEY (`id`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE `experiences` (
    `id` VARCHAR(191) NOT NULL,
    `workerId` VARCHAR(191) NOT NULL,
    `title` VARCHAR(191) NOT NULL,
    `company` VARCHAR(191) NOT NULL,
    `country` VARCHAR(191) NULL,
    `city` VARCHAR(191) NULL,
    `state` VARCHAR(191) NULL,
    `startDate` DATETIME(3) NOT NULL,
    `endDate` DATETIME(3) NULL,
    `currentlyWorking` BOOLEAN NOT NULL DEFAULT false,
    `description` TEXT NOT NULL,

    PRIMARY KEY (`id`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE `education` (
    `id` VARCHAR(191) NOT NULL,
    `workerId` VARCHAR(191) NOT NULL,
    `school` VARCHAR(191) NOT NULL,
    `degree` VARCHAR(191) NOT NULL,
    `fieldOfStudy` VARCHAR(191) NOT NULL,
    `startDate` DATETIME(3) NOT NULL,
    `currentlyStudying` BOOLEAN NOT NULL DEFAULT false,
    `endDate` DATETIME(3) NULL,
    `description` TEXT NULL,

    PRIMARY KEY (`id`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE `certificates` (
    `id` VARCHAR(191) NOT NULL,
    `workerId` VARCHAR(191) NOT NULL,
    `name` VARCHAR(191) NOT NULL,
    `issuingOrg` VARCHAR(191) NOT NULL,
    `issueDate` DATETIME(3) NOT NULL,
    `expiryDate` DATETIME(3) NULL,
    `credentialUrl` VARCHAR(191) NULL,

    PRIMARY KEY (`id`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE `assets` (
    `id` VARCHAR(191) NOT NULL,
    `key` VARCHAR(191) NOT NULL,
    `mediaType` VARCHAR(191) NOT NULL,
    `projectId` VARCHAR(191) NULL,
    `certificateId` VARCHAR(191) NULL,
    `createdAt` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),

    PRIMARY KEY (`id`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE `worker_languages` (
    `id` VARCHAR(191) NOT NULL,
    `workerId` VARCHAR(191) NOT NULL,
    `language` ENUM('ENGLISH', 'SPANISH', 'FRENCH', 'GERMAN', 'CHINESE', 'JAPANESE', 'ARABIC', 'RUSSIAN', 'PORTUGUESE', 'HINDI', 'ITALIAN', 'DUTCH', 'KOREAN', 'TURKISH', 'SWEDISH', 'POLISH', 'TAMIL', 'URDU', 'BENGALI', 'MARATHI', 'KANNADA', 'TELUGU', 'MALAYALAM', 'GUJARATI', 'PUNJABI', 'HARYANVI', 'KURDISH', 'AFRIKAANS', 'AZERBAIJANI', 'BULGARIAN', 'CROATIAN', 'CZECH', 'DANISH') NOT NULL,
    `proficiency` ENUM('BASIC', 'CONVERSATIONAL', 'FLUENT', 'NATIVE') NOT NULL,

    UNIQUE INDEX `worker_languages_workerId_language_key`(`workerId`, `language`),
    PRIMARY KEY (`id`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE `otps` (
    `id` VARCHAR(191) NOT NULL,
    `otp` INTEGER NOT NULL,
    `createdAt` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    `isExpired` BOOLEAN NOT NULL DEFAULT false,
    `userId` VARCHAR(191) NOT NULL,

    PRIMARY KEY (`id`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE `worker_skills` (
    `id` VARCHAR(191) NOT NULL,
    `workerId` VARCHAR(191) NOT NULL,
    `skillName` ENUM('PIPE_INSTALLATION', 'DRAIN_CLEANING', 'FIXTURE_INSTALLATION', 'WATER_HEATER_SERVICE', 'LEAK_REPAIR', 'WIRING_INSTALLATION', 'LIGHTING_INSTALLATION', 'ELECTRICAL_REPAIR', 'PANEL_UPGRADES', 'GENERATOR_INSTALLATION', 'CABINET_MAKING', 'FRAMING', 'FINISH_CARPENTRY', 'DOOR_INSTALLATION', 'WINDOW_INSTALLATION', 'AC_INSTALLATION', 'HEATING_REPAIR', 'VENTILATION_WORK', 'DUCT_CLEANING', 'SYSTEM_MAINTENANCE', 'INTERIOR_PAINTING', 'EXTERIOR_PAINTING', 'WALLPAPER_INSTALLATION', 'STAINING', 'PAINT_REMOVAL', 'LAWN_MAINTENANCE', 'TREE_TRIMMING', 'GARDEN_DESIGN', 'IRRIGATION_INSTALLATION', 'HARDSCAPING', 'DEEP_CLEANING', 'WINDOW_CLEANING', 'CARPET_CLEANING', 'PRESSURE_WASHING', 'SANITIZATION', 'FURNITURE_MOVING', 'PACKING_SERVICES', 'HEAVY_LIFTING', 'EQUIPMENT_TRANSPORTATION', 'LOGISTICS_PLANNING', 'ENGINE_REPAIR', 'BRAKE_SERVICE', 'TRANSMISSION_REPAIR', 'AUTO_ELECTRICAL', 'BODY_WORK', 'ROOF_INSTALLATION', 'SHINGLE_REPAIR', 'LEAK_DETECTION', 'GUTTER_INSTALLATION', 'ROOF_INSPECTION', 'BRICK_LAYING', 'STONE_WORK', 'CONCRETE_POURING', 'FOUNDATION_REPAIR', 'TUCKPOINTING', 'ARC_WELDING', 'MIG_WELDING', 'TIG_WELDING', 'PIPE_WELDING', 'STRUCTURAL_WELDING', 'TILE_INSTALLATION', 'HARDWOOD_FLOORING', 'CARPET_INSTALLATION', 'VINYL_FLOORING', 'FLOOR_REFINISHING', 'INSECT_EXTERMINATION', 'RODENT_CONTROL', 'TERMITE_TREATMENT', 'WILDLIFE_REMOVAL', 'PREVENTATIVE_TREATMENTS', 'REFRIGERATOR_REPAIR', 'WASHER_DRYER_SERVICE', 'DISHWASHER_REPAIR', 'OVEN_REPAIR', 'MICROWAVE_SERVICE', 'HANDYMAN_SERVICES', 'PROPERTY_MAINTENANCE', 'PREVENTATIVE_MAINTENANCE', 'EQUIPMENT_SERVICING', 'FACILITY_UPKEEP', 'SUPERVISOR', 'CONSTRUCTION_MANAGER', 'PROJECT_MANAGEMENT', 'TEAM_LEADERSHIP', 'RESOURCE_PLANNING', 'BUILDING_INSPECTION', 'SAFETY_INSPECTION', 'QUALITY_CONTROL', 'CODE_COMPLIANCE', 'STRUCTURAL_ASSESSMENT', 'INSTRUMENT_TECHNICIAN', 'MAINTENANCE_TECHNICIAN', 'ELECTRONICS_TECHNICIAN', 'CALIBRATION_SPECIALIST', 'EQUIPMENT_DIAGNOSTICS', 'PIPEFITTING', 'METAL_FABRICATION', 'WELDING_ASSEMBLY', 'STRUCTURAL_FABRICATION', 'CUSTOM_FABRICATION', 'EQUIPMENT_REPAIR', 'MECHANICAL_OVERHAUL', 'PLANT_MAINTENANCE', 'PREVENTIVE_MAINTENANCE', 'EXCAVATION', 'TRENCHING', 'SITE_CLEARANCE', 'LAND_GRADING', 'DEWATERING', 'CRANE_OPERATION', 'SLINGING', 'WINCHING', 'HOISTING', 'SCAFFOLD_RIGGING') NOT NULL,
    `createdAt` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),

    UNIQUE INDEX `worker_skills_workerId_skillName_key`(`workerId`, `skillName`),
    PRIMARY KEY (`id`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE `job_skills` (
    `id` VARCHAR(191) NOT NULL,
    `jobId` VARCHAR(191) NOT NULL,
    `skillName` ENUM('PIPE_INSTALLATION', 'DRAIN_CLEANING', 'FIXTURE_INSTALLATION', 'WATER_HEATER_SERVICE', 'LEAK_REPAIR', 'WIRING_INSTALLATION', 'LIGHTING_INSTALLATION', 'ELECTRICAL_REPAIR', 'PANEL_UPGRADES', 'GENERATOR_INSTALLATION', 'CABINET_MAKING', 'FRAMING', 'FINISH_CARPENTRY', 'DOOR_INSTALLATION', 'WINDOW_INSTALLATION', 'AC_INSTALLATION', 'HEATING_REPAIR', 'VENTILATION_WORK', 'DUCT_CLEANING', 'SYSTEM_MAINTENANCE', 'INTERIOR_PAINTING', 'EXTERIOR_PAINTING', 'WALLPAPER_INSTALLATION', 'STAINING', 'PAINT_REMOVAL', 'LAWN_MAINTENANCE', 'TREE_TRIMMING', 'GARDEN_DESIGN', 'IRRIGATION_INSTALLATION', 'HARDSCAPING', 'DEEP_CLEANING', 'WINDOW_CLEANING', 'CARPET_CLEANING', 'PRESSURE_WASHING', 'SANITIZATION', 'FURNITURE_MOVING', 'PACKING_SERVICES', 'HEAVY_LIFTING', 'EQUIPMENT_TRANSPORTATION', 'LOGISTICS_PLANNING', 'ENGINE_REPAIR', 'BRAKE_SERVICE', 'TRANSMISSION_REPAIR', 'AUTO_ELECTRICAL', 'BODY_WORK', 'ROOF_INSTALLATION', 'SHINGLE_REPAIR', 'LEAK_DETECTION', 'GUTTER_INSTALLATION', 'ROOF_INSPECTION', 'BRICK_LAYING', 'STONE_WORK', 'CONCRETE_POURING', 'FOUNDATION_REPAIR', 'TUCKPOINTING', 'ARC_WELDING', 'MIG_WELDING', 'TIG_WELDING', 'PIPE_WELDING', 'STRUCTURAL_WELDING', 'TILE_INSTALLATION', 'HARDWOOD_FLOORING', 'CARPET_INSTALLATION', 'VINYL_FLOORING', 'FLOOR_REFINISHING', 'INSECT_EXTERMINATION', 'RODENT_CONTROL', 'TERMITE_TREATMENT', 'WILDLIFE_REMOVAL', 'PREVENTATIVE_TREATMENTS', 'REFRIGERATOR_REPAIR', 'WASHER_DRYER_SERVICE', 'DISHWASHER_REPAIR', 'OVEN_REPAIR', 'MICROWAVE_SERVICE', 'HANDYMAN_SERVICES', 'PROPERTY_MAINTENANCE', 'PREVENTATIVE_MAINTENANCE', 'EQUIPMENT_SERVICING', 'FACILITY_UPKEEP', 'SUPERVISOR', 'CONSTRUCTION_MANAGER', 'PROJECT_MANAGEMENT', 'TEAM_LEADERSHIP', 'RESOURCE_PLANNING', 'BUILDING_INSPECTION', 'SAFETY_INSPECTION', 'QUALITY_CONTROL', 'CODE_COMPLIANCE', 'STRUCTURAL_ASSESSMENT', 'INSTRUMENT_TECHNICIAN', 'MAINTENANCE_TECHNICIAN', 'ELECTRONICS_TECHNICIAN', 'CALIBRATION_SPECIALIST', 'EQUIPMENT_DIAGNOSTICS', 'PIPEFITTING', 'METAL_FABRICATION', 'WELDING_ASSEMBLY', 'STRUCTURAL_FABRICATION', 'CUSTOM_FABRICATION', 'EQUIPMENT_REPAIR', 'MECHANICAL_OVERHAUL', 'PLANT_MAINTENANCE', 'PREVENTIVE_MAINTENANCE', 'EXCAVATION', 'TRENCHING', 'SITE_CLEARANCE', 'LAND_GRADING', 'DEWATERING', 'CRANE_OPERATION', 'SLINGING', 'WINCHING', 'HOISTING', 'SCAFFOLD_RIGGING') NOT NULL,
    `createdAt` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),

    UNIQUE INDEX `job_skills_jobId_skillName_key`(`jobId`, `skillName`),
    PRIMARY KEY (`id`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- AddForeignKey
ALTER TABLE `worker_profiles` ADD CONSTRAINT `worker_profiles_userId_fkey` FOREIGN KEY (`userId`) REFERENCES `users`(`id`) ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE `profile_pictures` ADD CONSTRAINT `profile_pictures_workerProfileId_fkey` FOREIGN KEY (`workerProfileId`) REFERENCES `worker_profiles`(`id`) ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE `business_profiles` ADD CONSTRAINT `business_profiles_userId_fkey` FOREIGN KEY (`userId`) REFERENCES `users`(`id`) ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE `user_restrictions` ADD CONSTRAINT `user_restrictions_userId_fkey` FOREIGN KEY (`userId`) REFERENCES `users`(`id`) ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE `conversations` ADD CONSTRAINT `conversations_workerProfileId_fkey` FOREIGN KEY (`workerProfileId`) REFERENCES `worker_profiles`(`id`) ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE `conversations` ADD CONSTRAINT `conversations_businessProfileId_fkey` FOREIGN KEY (`businessProfileId`) REFERENCES `business_profiles`(`id`) ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE `messages` ADD CONSTRAINT `messages_conversationId_fkey` FOREIGN KEY (`conversationId`) REFERENCES `conversations`(`id`) ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE `messages` ADD CONSTRAINT `messages_senderWorkerId_fkey` FOREIGN KEY (`senderWorkerId`) REFERENCES `worker_profiles`(`id`) ON DELETE SET NULL ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE `messages` ADD CONSTRAINT `messages_senderBusinessId_fkey` FOREIGN KEY (`senderBusinessId`) REFERENCES `business_profiles`(`id`) ON DELETE SET NULL ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE `messages` ADD CONSTRAINT `messages_receiverWorkerId_fkey` FOREIGN KEY (`receiverWorkerId`) REFERENCES `worker_profiles`(`id`) ON DELETE SET NULL ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE `messages` ADD CONSTRAINT `messages_receiverBusinessId_fkey` FOREIGN KEY (`receiverBusinessId`) REFERENCES `business_profiles`(`id`) ON DELETE SET NULL ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE `jobs` ADD CONSTRAINT `jobs_businessProfileId_fkey` FOREIGN KEY (`businessProfileId`) REFERENCES `business_profiles`(`id`) ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE `job_locations` ADD CONSTRAINT `job_locations_jobId_fkey` FOREIGN KEY (`jobId`) REFERENCES `jobs`(`id`) ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE `job_images` ADD CONSTRAINT `job_images_jobId_fkey` FOREIGN KEY (`jobId`) REFERENCES `jobs`(`id`) ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE `job_applications` ADD CONSTRAINT `job_applications_jobId_fkey` FOREIGN KEY (`jobId`) REFERENCES `jobs`(`id`) ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE `job_applications` ADD CONSTRAINT `job_applications_workerProfileId_fkey` FOREIGN KEY (`workerProfileId`) REFERENCES `worker_profiles`(`id`) ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE `contracts` ADD CONSTRAINT `contracts_jobId_fkey` FOREIGN KEY (`jobId`) REFERENCES `jobs`(`id`) ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE `contracts` ADD CONSTRAINT `contracts_workerProfileId_fkey` FOREIGN KEY (`workerProfileId`) REFERENCES `worker_profiles`(`id`) ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE `contracts` ADD CONSTRAINT `contracts_businessProfileId_fkey` FOREIGN KEY (`businessProfileId`) REFERENCES `business_profiles`(`id`) ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE `milestones` ADD CONSTRAINT `milestones_contractId_fkey` FOREIGN KEY (`contractId`) REFERENCES `contracts`(`id`) ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE `reviews` ADD CONSTRAINT `reviews_workerProfileId_fkey` FOREIGN KEY (`workerProfileId`) REFERENCES `worker_profiles`(`id`) ON DELETE SET NULL ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE `reviews` ADD CONSTRAINT `reviews_businessProfileId_fkey` FOREIGN KEY (`businessProfileId`) REFERENCES `business_profiles`(`id`) ON DELETE SET NULL ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE `reports` ADD CONSTRAINT `reports_reporterWorkerId_fkey` FOREIGN KEY (`reporterWorkerId`) REFERENCES `worker_profiles`(`id`) ON DELETE SET NULL ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE `reports` ADD CONSTRAINT `reports_reporterBusinessId_fkey` FOREIGN KEY (`reporterBusinessId`) REFERENCES `business_profiles`(`id`) ON DELETE SET NULL ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE `reports` ADD CONSTRAINT `reports_reportedWorkerId_fkey` FOREIGN KEY (`reportedWorkerId`) REFERENCES `worker_profiles`(`id`) ON DELETE SET NULL ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE `reports` ADD CONSTRAINT `reports_reportedBusinessId_fkey` FOREIGN KEY (`reportedBusinessId`) REFERENCES `business_profiles`(`id`) ON DELETE SET NULL ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE `projects` ADD CONSTRAINT `projects_workerId_fkey` FOREIGN KEY (`workerId`) REFERENCES `worker_profiles`(`id`) ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE `experiences` ADD CONSTRAINT `experiences_workerId_fkey` FOREIGN KEY (`workerId`) REFERENCES `worker_profiles`(`id`) ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE `education` ADD CONSTRAINT `education_workerId_fkey` FOREIGN KEY (`workerId`) REFERENCES `worker_profiles`(`id`) ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE `certificates` ADD CONSTRAINT `certificates_workerId_fkey` FOREIGN KEY (`workerId`) REFERENCES `worker_profiles`(`id`) ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE `assets` ADD CONSTRAINT `assets_projectId_fkey` FOREIGN KEY (`projectId`) REFERENCES `projects`(`id`) ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE `assets` ADD CONSTRAINT `assets_certificateId_fkey` FOREIGN KEY (`certificateId`) REFERENCES `certificates`(`id`) ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE `worker_languages` ADD CONSTRAINT `worker_languages_workerId_fkey` FOREIGN KEY (`workerId`) REFERENCES `worker_profiles`(`id`) ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE `otps` ADD CONSTRAINT `otps_userId_fkey` FOREIGN KEY (`userId`) REFERENCES `users`(`id`) ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE `worker_skills` ADD CONSTRAINT `worker_skills_workerId_fkey` FOREIGN KEY (`workerId`) REFERENCES `worker_profiles`(`id`) ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE `job_skills` ADD CONSTRAINT `job_skills_jobId_fkey` FOREIGN KEY (`jobId`) REFERENCES `jobs`(`id`) ON DELETE CASCADE ON UPDATE CASCADE;
